<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Welcome rohith</name>
   <tag></tag>
   <elementGuidId>9a8403a3-4ec4-4f77-a737-79c203b5daff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#welcome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='welcome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30fc09ed-4522-4d44-a0df-fdb520ab21c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a4c0e4ed-a015-4a3b-8124-72618d61adf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>welcome</value>
      <webElementGuid>1dc4d97f-7408-4963-b17f-c25f72fb75a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panelTrigger</value>
      <webElementGuid>1d56c841-668d-4c67-b94f-d227bd8794c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome rohith</value>
      <webElementGuid>553d1186-f8f1-4ced-a2bc-7a76fb9c1f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;welcome&quot;)</value>
      <webElementGuid>dbd818bb-5d71-4121-b60e-597aefab1988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='welcome']</value>
      <webElementGuid>4aceea55-8739-4bf7-aeb5-d08ad8a6cde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='branding']/a[2]</value>
      <webElementGuid>8ca1ea42-9552-4c6b-97e2-bf527a5575b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Welcome rohith')]</value>
      <webElementGuid>7a20a432-a9a6-43a1-8507-4ef7e438dfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No new notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>3fe9134c-ff37-4d12-92fd-70ac368d6b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success!'])[1]/preceding::a[1]</value>
      <webElementGuid>4b9147ba-b38d-4b24-936a-e20c8cf67c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome rohith']/parent::*</value>
      <webElementGuid>a41610e7-973a-4a5c-b70b-87758ef7c121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>3c8571a1-1066-47ff-9bf5-dff426696622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>7b4f2b53-5a57-4802-9c3a-63383fdddfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'welcome' and (text() = 'Welcome rohith' or . = 'Welcome rohith')]</value>
      <webElementGuid>4615eb07-a8bb-42ac-8800-a2973ea3d0cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
