<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Titles_btnDelete</name>
   <tag></tag>
   <elementGuidId>b757e93f-f6d9-4408-bb33-6ec5417443b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed78a56-509a-48be-ac4f-8aaa5abd8141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5de7033d-67b8-4a19-a68f-8129f9026fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete hover</value>
      <webElementGuid>07a8bef4-7451-4f6b-b1d4-4af201254074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>c214eb57-0649-428b-8fbe-552382766439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>036fdb6d-8112-4f98-8781-68f7a300a1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e13c27b9-be82-48ca-9120-71b2f5ada609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>44569d81-968e-470a-a49a-323581d91014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#deleteConfModal</value>
      <webElementGuid>02e62c2a-e8ec-4497-9f6d-f03516bd2ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDelete&quot;)</value>
      <webElementGuid>a4976370-2e94-47e4-8c0e-070fff3e39dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnDelete']</value>
      <webElementGuid>78eb8a7f-9ee9-4d90-b90e-1bf67646589e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input[2]</value>
      <webElementGuid>bcb53101-bdc6-414c-8d22-bd634b8d51d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>10fcc265-2b01-4e8f-ab7f-73b085a5b172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnDelete' and @name = 'btnDelete']</value>
      <webElementGuid>34c34324-2ce7-4969-a239-c083dbc6b822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
