<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_abctestdesc_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>d1d10205-b343-4215-9c47-eb92e142005a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_48</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/tbody/tr[3]/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb79c299-0231-43d3-9c8d-53dc9ccf0664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>292665d1-3222-4e8e-bbde-4ce814353319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_48</value>
      <webElementGuid>e47548b9-e83d-4241-9e20-04030e8fd81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>42fbbe0b-56e5-42c7-84d7-e48ebd653755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>f39fc573-64f3-48a7-9311-5a2347e8ce78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_48&quot;)</value>
      <webElementGuid>2209789f-dd01-4eb7-9347-2a95b96f6b80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_48']</value>
      <webElementGuid>7ad1cb64-bf32-4ece-b33f-52b722c2e84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[3]/td/input</value>
      <webElementGuid>6239091f-e859-4fe9-b0c1-77102dcc8f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>42cb148a-985f-4813-8030-58630756b6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_48' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>f4492b2f-6a82-475f-8947-8093134abd4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
