<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Categories_btnDelete</name>
   <tag></tag>
   <elementGuidId>64c89539-1ef2-4e17-a1b1-3febf87c7d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e3bd558-a579-4c48-8940-4b1ae9324425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a86dfb88-6dce-4b1c-bf9e-be21415247cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete hover</value>
      <webElementGuid>266264e6-3769-45ed-aab5-a8936788b4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>afaef440-acc6-4dcb-87c2-f145aaacde67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>4dd13904-3f5c-4105-a236-965d53bbe4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>68a6af7f-9190-4a0f-a8db-70c2dc0fac5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>69d4eaaa-6bb9-4123-ba91-49c606f0c21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#deleteConfModal</value>
      <webElementGuid>4f16ea3f-ae16-41c6-88e9-541e8b4ce6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDelete&quot;)</value>
      <webElementGuid>fe46eab4-53fd-4237-9678-3bbcfcee97d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnDelete']</value>
      <webElementGuid>74fe8bb5-d348-42e1-88b9-5f12b4415073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input[2]</value>
      <webElementGuid>c790a566-47f4-4603-a780-ae835d94eab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>4141befb-39d0-40b9-938e-90ba800f6787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnDelete' and @name = 'btnDelete']</value>
      <webElementGuid>2ace0858-bf7e-439e-a02f-cb79db8a790e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
