<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atest_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>a91b15f7-1e94-4e9c-a79b-3350358457e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/tbody/tr[2]/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8e718f9-ed33-46fd-9f04-76a7996a5e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f18ed4be-ec3c-4bb9-a4e4-79d4443bab2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_21</value>
      <webElementGuid>8116a101-bc2e-4df6-bb81-1151fb1f778a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>89725ec5-d804-4875-a256-7dec82901332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>2ff1f4a3-44f1-43f2-9a70-fecba52e237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_21&quot;)</value>
      <webElementGuid>e55d41e9-2d85-4065-9700-b80d0239770d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_21']</value>
      <webElementGuid>7d1260d3-edff-4da1-9321-f7c241da583f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[2]/td/input</value>
      <webElementGuid>ad7f2101-5352-46ff-b00b-5e5b4b0219a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>7b1fd32f-6776-4a80-bc90-37c4bbbfe580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_21' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>c2b30746-b4e2-41b2-8802-f536beaed030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
