<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Categories_btnDelete</name>
   <tag></tag>
   <elementGuidId>8a176fc7-5e79-463d-9793-3144abc2a8d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6266f09f-9a13-4212-b071-8cff6ac124e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4e745e32-ddcd-4b1c-9dda-055c34a6d3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete hover</value>
      <webElementGuid>75d67bb7-a6fc-4110-afdb-12a59dfa5801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>245bfa59-92ee-45d1-bf24-81eaaa9478eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>b05e046e-0496-4379-9ba9-a7bb7614383d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e1f05467-78da-4fd0-a7a5-58fb7438727f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>7b81a758-c2f8-4144-be0d-9020cc761763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#deleteConfModal</value>
      <webElementGuid>16e5d787-582a-4b99-8b60-6db33e74358f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDelete&quot;)</value>
      <webElementGuid>5d91f739-e288-46c3-9938-6a06313ea28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnDelete']</value>
      <webElementGuid>75564d91-d47b-4658-91a3-81d27afba2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input[2]</value>
      <webElementGuid>593521d3-6ed5-46b7-9f20-944a0ee21743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>ff07377d-ff70-4e8d-94cb-4f2b6afe7262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnDelete' and @name = 'btnDelete']</value>
      <webElementGuid>0912d94f-19f3-44fa-b1d6-ebbbe9e3a2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
