<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Content Specialist_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>5933ec5f-7435-4e78-9ed9-b957c7aca237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ohrmList_chkSelectRecord_35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26f43583-7df8-479d-982e-d6c6067e1be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58d74545-9b9a-44b3-be8c-86667ee79760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_35</value>
      <webElementGuid>094de656-c09e-4bc7-a6d3-770e53ce1488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>3a52c4e1-7f58-437a-8c9b-8049524e74c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>880013e2-1d04-4a19-98fc-22f5ce600703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_35&quot;)</value>
      <webElementGuid>e2e9fedc-c30a-4721-a585-ae9a89706c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_35']</value>
      <webElementGuid>00a182b3-6f4a-403b-a720-5b3c61ff7bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[6]/td/input</value>
      <webElementGuid>aff36819-50ae-4061-bc09-5a25bf7a90db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>f445edb6-acb2-48d1-9dd5-d167aa2aff08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_35' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>a0a7af18-65c6-4a68-9a52-7b986478908b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
