<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobTitlejobTitle</name>
   <tag></tag>
   <elementGuidId>c68f4c5a-19d4-4b30-8652-418587852a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTitle_jobTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_jobTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1069c3a9-8fb2-4939-aede-29c87dfa7c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0abfb4c1-f052-440f-b18a-aaef7832f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[jobTitle]</value>
      <webElementGuid>ea2d2e03-74c2-4747-85e7-a3d09d6e3d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8ca266dc-8d87-4aba-bb01-85126530d359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_jobTitle</value>
      <webElementGuid>6d809582-a606-431e-8df1-7ab58939e5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>b0cf5235-709a-4c06-a26c-2e8e9f0276c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_jobTitle&quot;)</value>
      <webElementGuid>9670938f-89d3-49b1-b074-447e7c34ee7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTitle_jobTitle']</value>
      <webElementGuid>304fffb1-84d7-45d6-92e3-3bf4fa17f6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li/input</value>
      <webElementGuid>833cd54e-66eb-4e79-b5da-9a7cd7d919b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>7a19827e-3a8d-4c17-a427-67324f12c14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobTitle[jobTitle]' and @id = 'jobTitle_jobTitle']</value>
      <webElementGuid>4e0b9a6c-8a3d-4d57-9225-f5d8c7b1875b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
