<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM - Confirmation Required_dia_9fc7db</name>
   <tag></tag>
   <elementGuidId>d86ec193-b4e8-482f-addd-732f9d00511f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialogDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4291503-3706-4b1e-be42-a094b2c0ec1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3853ee9e-829f-4f35-a819-f316ad81e5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hover</value>
      <webElementGuid>25b14984-8acc-4c01-bebd-9950e4e5b94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>ae0660fe-c51f-4f15-93e9-81dc2c7ce042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogDeleteBtn</value>
      <webElementGuid>88fd0fc4-cd25-49aa-952a-04543968d043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>af22acd7-4065-4e92-a185-7a51fe470377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogDeleteBtn&quot;)</value>
      <webElementGuid>dac72b38-1d90-4c59-a7a2-b9db259d256d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogDeleteBtn']</value>
      <webElementGuid>d56cbf1b-f9cb-4923-b2ec-72e9527984d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfModal']/div[3]/input</value>
      <webElementGuid>0c65b61f-8830-4b7c-9b08-608c4fbcad29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>001a10c0-4e68-4769-98db-c4e45c1404b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogDeleteBtn']</value>
      <webElementGuid>e8dcfa95-79b7-4cbb-9c87-cc7f60c41ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
