<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>65cca539-8d0b-4e5e-bc8b-53d3e4f03872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treeLink_addChild_13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='treeLink_addChild_13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a274c58-ac79-4cad-9249-e391fb749155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?</value>
      <webElementGuid>73fa6f98-4462-43ce-a626-09ebd4e64af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeLink_addChild_13</value>
      <webElementGuid>18172e6a-2b66-43fd-9a14-ecc78b1f4854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addButton</value>
      <webElementGuid>a26b9179-0454-41fc-9e48-99971084ba9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +</value>
      <webElementGuid>dd8aa290-562c-418f-a745-5ec5dd037099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeLink_addChild_13&quot;)</value>
      <webElementGuid>550a33b8-a010-4338-a502-182cace934e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='treeLink_addChild_13']</value>
      <webElementGuid>11f94c92-8a83-4e56-873f-7872242c6d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='node_13']/a[2]</value>
      <webElementGuid>3677357f-3ed2-4de6-8941-d872eb6e1ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'+')])[13]</value>
      <webElementGuid>87b8ac5f-f9f1-45fc-8483-be6bdea0addb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Human Resources'])[2]/following::a[1]</value>
      <webElementGuid>f1ead395-9d37-4772-a014-f57027b4a3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Human Resources'])[1]/following::a[2]</value>
      <webElementGuid>a6972170-4f73-4801-a024-1faa7ada25f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[12]/preceding::a[1]</value>
      <webElementGuid>ecb57a81-fce7-4076-a286-4d4932d6ae61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[2]</value>
      <webElementGuid>a22519df-6042-46c6-adb9-e8ef376605af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#?')])[37]</value>
      <webElementGuid>fdc8cbae-c643-4a6a-a22d-5d3f73e3c479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a[2]</value>
      <webElementGuid>60b7a01d-a22a-461e-abc9-840e08cfe574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?' and @id = 'treeLink_addChild_13' and (text() = ' +' or . = ' +')]</value>
      <webElementGuid>48627d3d-6932-4806-adda-103573e0ccdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
