<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_x</name>
   <tag></tag>
   <elementGuidId>28489452-4abb-4226-a72b-26c2d3dc9500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#?' and @id = 'treeLink_delete_21' and (text() = ' x' or . = ' x')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeLink_delete_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='treeLink_delete_21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36bac861-3b77-4af8-8f87-73a348214b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?</value>
      <webElementGuid>8163cb75-da8e-411a-a3a6-3d61c0d8f97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeLink_delete_21</value>
      <webElementGuid>ff4d65d6-3831-46cf-8f54-fb7e226a16cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deleteButton katalonHighlight</value>
      <webElementGuid>237224e0-48c4-45e9-a113-19fd1d98c73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x</value>
      <webElementGuid>fc858132-2fba-480e-bdf8-f18a7a6d2aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeLink_delete_21&quot;)</value>
      <webElementGuid>2b800267-69be-4230-9929-00d5dc47f44e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='treeLink_delete_21']</value>
      <webElementGuid>b31bb2a3-fe62-4112-8d88-54cba443fd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='node_21']/a[3]</value>
      <webElementGuid>3d78fefd-e6c8-46e7-83ad-085bc2f966b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'x')])[13]</value>
      <webElementGuid>937345f7-5a3b-4624-b769-2fb0488f46f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[14]/following::a[1]</value>
      <webElementGuid>0b7347ed-e03c-49df-958c-d95df01318f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testA'])[2]/following::a[2]</value>
      <webElementGuid>b6ff0e68-d232-44ad-b5ed-80583a64a5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[1]</value>
      <webElementGuid>c057a114-41f2-4f7e-9646-e418cb6acc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM - Edit Unit'])[1]/preceding::a[2]</value>
      <webElementGuid>fc9d0418-4c38-4a67-8aba-603e12a021f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#?')])[41]</value>
      <webElementGuid>9909243e-1058-486a-b036-306a26c143bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a[3]</value>
      <webElementGuid>44da9060-9de3-46b3-97bc-6db954c0bea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?' and @id = 'treeLink_delete_21' and (text() = ' x' or . = ' x')]</value>
      <webElementGuid>8512a42f-c43c-4604-84b8-cbeacc77ae6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
