<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_btnEdit</name>
   <tag></tag>
   <elementGuidId>2eb76f94-85db-4a3a-adc1-49bfef0f3876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnEdit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d19beded-7da5-4901-b807-842453145fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94fa2434-2ed4-4363-aefa-34fecc1b3541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>9ad4608d-2501-49a8-83d2-f6d2c0c8cc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnEdit</value>
      <webElementGuid>a5d8da17-1155-4d93-8afa-8322f4385ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEdit</value>
      <webElementGuid>2fbcce24-81c8-4deb-a4f7-d176dc02fef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>8219db01-13ad-4ec6-9ba4-dab8a708a838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEdit&quot;)</value>
      <webElementGuid>bc58eae7-a459-41b9-8bf2-af52b610e969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnEdit']</value>
      <webElementGuid>9211b8a2-1eda-4bb5-b959-7edf45b1bfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/p/input</value>
      <webElementGuid>aaa3f04a-d852-44b0-af88-8fd076162ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>9cbb9486-10f0-46bf-9c17-3348e81024e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnEdit' and @id = 'btnEdit']</value>
      <webElementGuid>d5ff4482-74e9-4115-9982-6baf2e965a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
