<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM - Confirmation Required_dia_9fc7db</name>
   <tag></tag>
   <elementGuidId>fd1edbf3-77b3-429d-9c50-ee3f8d5a5a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dialogDeleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogDeleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c36c1143-87ee-4207-b910-9929ed04103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7308e30-17d3-458f-983b-3a7fb24676aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hover</value>
      <webElementGuid>d21ae6d0-cfdc-438c-a411-30a789bf26bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>7ded6ffe-a255-4024-9e9f-b09d4c697138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogDeleteBtn</value>
      <webElementGuid>5410f64c-e2aa-4f7a-8f8e-b0648ba27eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>13abcd9e-3005-4026-81af-beb8d6771d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogDeleteBtn&quot;)</value>
      <webElementGuid>7e1abbf7-ca45-40ba-a984-e4fbc09c0641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogDeleteBtn']</value>
      <webElementGuid>ba8f8c17-cdc1-441f-b8d4-f927d982e9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfModal']/div[3]/input</value>
      <webElementGuid>a7b95867-6f88-45bd-86b8-21527b1ca532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>34c34376-c972-4601-9071-a154df5d7833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogDeleteBtn']</value>
      <webElementGuid>becaa239-0d65-41e6-ada9-c2f06ab5fcb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
