<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobCategoryname</name>
   <tag></tag>
   <elementGuidId>c0e1d235-1a25-44a3-8aee-d5251494fc3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobCategory_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobCategory_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2556a84-9c68-4972-b1b5-347a40924f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71bbbaf0-a272-4d69-8383-d245625e6642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobCategory[name]</value>
      <webElementGuid>7a1d4322-d5a8-45e2-b979-5d75b7f8aae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>bcca7e09-a9fd-436e-9029-d0ed6d9729c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>3e8e98f2-2d45-4f63-9a14-dcdf7a7122cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobCategory_name</value>
      <webElementGuid>7a6ee6ef-223f-48d1-88ff-a9d5bda396e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobCategory_name&quot;)</value>
      <webElementGuid>9d7d7232-d43e-47f6-9f90-6531676d8236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobCategory_name']</value>
      <webElementGuid>ffcbadc7-8b46-47ab-8a09-332a9701d305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmJobCategory']/fieldset/ol/li/input</value>
      <webElementGuid>bb6a5acb-d9f3-4558-8268-6ee628735650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>3762aae5-2a4c-4dad-b211-eaf6a02cbb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobCategory[name]' and @id = 'jobCategory_name']</value>
      <webElementGuid>7dbf8082-6a4e-4335-b103-c6a650400c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
