<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report Name_searchsearch</name>
   <tag></tag>
   <elementGuidId>11c2397f-b43b-43b3-bfc7-decedf44e507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e322b872-1258-4910-b59f-954244e98bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81b588fe-61f2-4d7a-b52c-93552f933abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search[search]</value>
      <webElementGuid>d4396b58-cc0e-4245-b2df-361d77288938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_search</value>
      <webElementGuid>e316f3ab-320f-4d2e-8aff-3c374c44966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>89ad2ad9-e968-47d4-8acc-ab4f4d8c0878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>cad00ef3-94dd-4491-837a-e7268d74a8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_search&quot;)</value>
      <webElementGuid>4992d528-f071-4c56-bdfd-9f32abae2d2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_search']</value>
      <webElementGuid>aa2cd00d-a827-4b00-87b9-aaad4406c109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/ol/li[2]/input</value>
      <webElementGuid>6c64855a-bcd5-45e4-b1d9-5903c3c1b1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>71f83677-9a98-44d5-86ae-ace910200e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search[search]' and @id = 'search_search']</value>
      <webElementGuid>a37c8ee2-b704-4e23-98e7-91ed7e987e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
