<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reportreport_name</name>
   <tag></tag>
   <elementGuidId>897b91e8-90bc-4962-9f22-834b62d06198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_report_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='report_report_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2898fe2-ffa6-4c7a-844b-1c435b9a1bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4566f655-9ed8-4673-b744-a8f9789b7abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>report[report_name]</value>
      <webElementGuid>956ce7c2-7bd4-4dce-b29e-afe86daaa3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_report_name</value>
      <webElementGuid>7ac73ddc-0f2c-4a63-9f25-4b018d63070b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>7fa8d149-3882-482a-81c7-8c4787b06680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_report_name&quot;)</value>
      <webElementGuid>2c14c631-9133-4cb1-8ae6-982a4fccee22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='report_report_name']</value>
      <webElementGuid>1e8d5bc9-4707-4c5a-bb4e-3f4051299c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='name_fieldset']/ol/li/input</value>
      <webElementGuid>a786a3d5-0030-410b-9f92-832ef3affda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>fa4d761b-720a-4963-9ae7-56439059a9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'report[report_name]' and @id = 'report_report_name']</value>
      <webElementGuid>c82b03b8-ad1e-4799-85cd-d17d107bb643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
