<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobCategoryname</name>
   <tag></tag>
   <elementGuidId>350107c7-597c-4f93-a9be-ba79aa4c8e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobCategory_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobCategory_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe7b40e-5b23-46ef-9c96-5350dda8a7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95844846-61c8-446d-8ed3-0fa4494e14bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobCategory[name]</value>
      <webElementGuid>2ef2ef78-3627-41cd-9c44-d0f14a61b904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>3a155f9b-50ff-4c36-8310-b569d7bd03ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>480102ed-4d48-4e23-976c-5c573116ecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobCategory_name</value>
      <webElementGuid>8536d252-8db2-42ce-8b14-02f7384ad49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobCategory_name&quot;)</value>
      <webElementGuid>953903a8-ae6f-4e81-ad6d-3888c430f60f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobCategory_name']</value>
      <webElementGuid>fcedb4a1-d547-4512-89e5-46fe130df397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmJobCategory']/fieldset/ol/li/input</value>
      <webElementGuid>303e177e-ddee-4499-88a1-125c435ec7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ec2af114-2c09-4f56-ba00-8c6f15739e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobCategory[name]' and @id = 'jobCategory_name']</value>
      <webElementGuid>3a5db2c5-cf53-4e19-9266-c18ac9bc4b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
