<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobCategoryname</name>
   <tag></tag>
   <elementGuidId>aaf81048-64cb-4f86-8043-862cbc551da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobCategory_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobCategory_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9017127b-4ada-4367-a72f-0f6817ad2d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9bc3b23-0bb4-4ddf-acd1-ec85e275900f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobCategory[name]</value>
      <webElementGuid>b660d6b8-be34-4919-927c-16aaeb59a35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>0a415a1b-cb70-4ab1-b562-3c20c3e5f283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>7fb3cce7-5019-4204-8263-5af7cce765b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobCategory_name</value>
      <webElementGuid>b3281ab1-6377-44ed-bdd0-ede3cf7359e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobCategory_name&quot;)</value>
      <webElementGuid>e73383bb-435d-416c-9150-4c0d43c11ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobCategory_name']</value>
      <webElementGuid>573b0f58-5cf0-46eb-931d-516f153d4eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmJobCategory']/fieldset/ol/li/input</value>
      <webElementGuid>93e72bc6-d05f-4df1-a30c-370a02fb5d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>f1a2993c-5971-454c-b12a-e24a793af59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobCategory[name]' and @id = 'jobCategory_name']</value>
      <webElementGuid>34bff8c4-649f-4735-9c06-435e042c873f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
