<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report Name_searchsearch</name>
   <tag></tag>
   <elementGuidId>a8675940-3adf-42a0-aad8-d59c678183f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b7e02e9-0617-4c3e-9b5e-36cbd4ef48a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32e1483c-278b-45ac-a892-6eccdb09304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search[search]</value>
      <webElementGuid>d07f8021-c0de-41c3-911a-5affc7e03bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_search</value>
      <webElementGuid>12e2249d-4d6b-4add-9cef-376316e41736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83ee1ca2-c0d2-456f-a7bb-1b14439fc356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>f472b4e6-2ac4-4d63-a4b8-8baf73d7494a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_search&quot;)</value>
      <webElementGuid>773d8ee1-3fde-4ef1-a16b-454c389bbce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_search']</value>
      <webElementGuid>a859daf0-ef9a-4f62-9c3c-a3f719115560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/ol/li[2]/input</value>
      <webElementGuid>610bdc07-85d4-4d00-a6e3-a8bf75042928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>cdfe7323-58ae-46f6-b1ec-7387b7a6e880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search[search]' and @id = 'search_search']</value>
      <webElementGuid>8cab59cc-1400-40f1-afc1-0022b4017433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
