<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job</name>
   <tag></tag>
   <elementGuidId>eeeb6647-535b-40a5-8dbf-e272b38ed696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_admin_Job</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_admin_Job']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26da7909-0a07-480f-b1d0-cb10db09e6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b3c787dd-ea44-4bc0-b92c-3ed92c9dbc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_admin_Job</value>
      <webElementGuid>1c857a33-87c7-452c-9cf3-b4c5adbf4194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>65fb5f32-7b84-4d37-a5f2-c3b6965b170e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job</value>
      <webElementGuid>798e6154-ab52-4e2f-bbcb-43777e0f4321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_admin_Job&quot;)</value>
      <webElementGuid>d60b8806-b3f9-4c93-9e47-d7087562b64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_admin_Job']</value>
      <webElementGuid>76b669a8-a26e-4c2c-a8cc-ddd7fff1808d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li/ul/li[2]/a</value>
      <webElementGuid>c95a20e7-98a4-4037-88fc-4ef7ac384e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job')]</value>
      <webElementGuid>cff44546-738b-47ff-b3e1-d81df41eee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[1]</value>
      <webElementGuid>c3bb7f9a-c462-4339-bbf4-ab62daab9250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::a[3]</value>
      <webElementGuid>82bdf29b-d4e5-4173-9f3d-2ba029da2e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Titles'])[1]/preceding::a[1]</value>
      <webElementGuid>7c665313-6b1e-41d5-9961-14b01e92d3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Grades'])[1]/preceding::a[2]</value>
      <webElementGuid>77e68586-f379-4285-a378-4df1ce33d929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job']/parent::*</value>
      <webElementGuid>b21d3bfa-0897-431e-bc39-7839e2420cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>e5a7a3ce-6778-4ff1-b888-3aab5e564de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/a</value>
      <webElementGuid>e7997f6b-4b3c-4afc-a3f2-f7aa7aca93b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'menu_admin_Job' and (text() = 'Job' or . = 'Job')]</value>
      <webElementGuid>06fa4c9c-be7d-4d15-b029-3e57fcda3825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
