<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobTitlejobTitle</name>
   <tag></tag>
   <elementGuidId>38fe4842-27f3-4dbb-b05e-aa3c0688c547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_jobTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTitle_jobTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7853685e-353c-4563-bb96-4496be2f64dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19f21da5-8526-4dc4-b5d6-7bd381630c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[jobTitle]</value>
      <webElementGuid>d4fcc3a2-7dc7-4bac-81aa-2a3fed2d4115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2c7ec9c4-fdfa-484e-84f3-6687b35d132a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_jobTitle</value>
      <webElementGuid>42ca1bad-1332-48f9-b093-403f62a3938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_jobTitle&quot;)</value>
      <webElementGuid>20cfc780-d343-452a-ba0b-f5f84649eef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTitle_jobTitle']</value>
      <webElementGuid>ff93e88e-4f0a-42b2-ad38-f232b01d6b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li/input</value>
      <webElementGuid>3cfb314c-6c44-4e2c-ae29-7962be323c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>3ede62ba-0aa0-4a00-ba3f-ce96b0487542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobTitle[jobTitle]' and @id = 'jobTitle_jobTitle']</value>
      <webElementGuid>e5deb814-da0e-419a-bc76-866f88453da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
