<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Job Description_jobTitlejobDescription</name>
   <tag></tag>
   <elementGuidId>03e3dce4-eba1-4eec-a31d-4250176f24ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_jobDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='jobTitle_jobDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1867ff55-f447-4ba4-9247-3c0399b9e967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bd6c160e-25c8-424d-b9eb-7f0a89d2ed33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>0383af26-524b-4730-a4f1-2cc1a9b233b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[jobDescription]</value>
      <webElementGuid>08fdce9c-3eb6-4209-8334-acdbd23d9ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>5ad76056-9dee-4130-b509-2dcd827b18cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_jobDescription</value>
      <webElementGuid>cbe5e95a-4cc7-4a30-a226-9ce9ea92f88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_jobDescription&quot;)</value>
      <webElementGuid>84c62c93-22a8-4c77-a6c5-9eb3cef0b777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='jobTitle_jobDescription']</value>
      <webElementGuid>9045cf37-5397-49ed-8ce0-1931d0d30c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li[2]/textarea</value>
      <webElementGuid>44a4def3-c622-4e29-9108-5ffe7248f376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>da464497-0493-4906-ac3c-b8914c6d3921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'jobTitle[jobDescription]' and @id = 'jobTitle_jobDescription']</value>
      <webElementGuid>3a9ad5e7-b503-403f-89e8-291ffe8d0584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
